### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by Arfirik** [Darayavaush/decensooru#14]
So i did everything that was said in the installation instruction, there were 2 qick pop-ups in the corner, but nothing happened, everything is still hidden. Please help if you're still here.

**Comment by Darayavaush** [comment]
Hm, 2 popups are a good sign, but the first one should have been fairly long.

After opening any page on Danbooru check the dev console (F12 - Console). There should be an entry "Decensooru started. There are X items in the DB". Does it say that?

**Comment by Arfirik** [comment]
It does say that, yes.

**Comment by Darayavaush** [comment]
How many items does it say there are?

**Comment by Arfirik** [comment]
Sorry for the late reply, i've been busy.
It says there's 138 items in the DB.

**Comment by Arfirik** [comment]
The first popup was "Decensooru is pulling a full batch…" and the second one is "Done." by the way.
Also, i don't know if this is related in any way, but there's a pop up on the top from Better Better Booru that says "Error checking account settings (HTML Code: 404 )."

**Comment by Darayavaush** [comment]
Hm, looks like the initial download was interrupted somehow. In the footer of every Danbooru page there should be a link "force full refresh of Decensooru"; click it once, wait until the "Done" popup appears, then check the console and tell me how many files it says there are in the DB.

**Comment by Arfirik** [comment]
Now it says there's 85169 files in the DB, but everything is still hidden.

**Comment by Darayavaush** [comment]
Hmm. To make sure we're on the same page - if you go to https://danbooru.donmai.us/posts?tags=banned_artist&page=&limit=72 , you see many white thumbnails with a black border and "Hidden" text (and _NOT_ empty space); if you click on the last image on the search page, you go to an image page where you have the tag string instead of the image (so it looks like this - 
![image](https://user-images.githubusercontent.com/3651004/77466055-5acbe500-6e12-11ea-94ca-c1b17708b347.png) ) (and _NOT_ simply "Artist requested removal of this page" like this - 
![image](https://user-images.githubusercontent.com/3651004/77466376-d9c11d80-6e12-11ea-933b-fc80cec404f5.png) ).
Correct?

**Comment by Arfirik** [comment]
It actually simply says "The artist requested removal of this page" like on the second screenshot.

**Comment by Darayavaush** [comment]
That means that you didn't properly modify the BBB code as it says in the instructions ("Artist requested removal" is the default BBB message, indicating unmodified code). Please reinstall BBB and carefully go through the instructions.

**Comment by Arfirik** [comment]
This is weird, the code wasnt modified because i did a reinstall just before starting this issue and forgot to modify it, but i did modify it before and it didn't work.
And now it works, though a couple of posts are still hidden.
I guess the problem is solved, dunno why it wasn't working before even though i modified the code, but anyways, thanks a lot for your time!
